[package]
name = "maze-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.9.0"
winit = "0.26.1"
winit_input_helper = "0.11.1"
anyhow = "*"
rand = "0.8.5"
